const dashboardStrings = {
  nav: {
    dashboard: "dashboard",
    profile: "profile",
    logOut: "log out",
    tabs: {
      content: "content",
      packages: "packages",
      games: "games",
    },
  },

  games: {
    tabs: {
      games: "games",
      developers: "developers",
      publishers: "publishers",
      genres: "genres",
      themes: "themes",
      platforms: "platforms",
    },
    sections: {
      games: "games library",
      developers: "game developers",
      publishers: "game publishers",
      genres: "game genres",
      themes: "game themes",
      platforms: "game platforms",
    },
    buttons: {
      newGame: "+ new game",
      newDeveloper: "+ new developer",
      newPublisher: "+ new publisher",
      newGenre: "+ new genre",
      newTheme: "+ new theme",
      newPlatform: "+ new platform",
      edit: "edit",
      delete: "delete",
      cancel: "cancel",
      saveChanges: "save changes",
      saving: "saving...",
      createGame: "create game",
      createDeveloper: "create developer",
      createPublisher: "create publisher",
      createGenre: "create genre",
      createTheme: "create theme",
      createPlatform: "create platform",
      gridView: "grid view",
      listView: "compact row list view",
    },
    search: {
      games: "search games by title or slug...",
      template: "search {type} by name or slug...",
    },
    empty: {
      noMatch: 'no {type} match your search query: "{q}"',
      noResults: "no {type} found.",
    },
    card: {
      release: "release:",
      hltb: "hltb:",
      metacritic: "mc:",
      opencrit: "oc:",
      global: "global",
    },
    modalTitle: {
      edit: "edit {type}",
      new: "new {type}",
    },
    form: {
      coreInfo: "core info",
      title: "title",
      slug: "slug",
      originalTitle: "original title (optional)",
      description: "description (optional)",
      coverImageUrl: "cover image url (optional)",
      releaseDate: "release date (optional)",
      metacriticScore: "metacritic score (optional)",
      opencriticScore: "opencritic score (optional)",
      hltbMain: "hltb main (h)",
      hltbMainEx: "hltb main+ex (h)",
      hltbComp: "hltb comp (h)",
      relations: "relations",
      developers: "developers",
      publishers: "publishers",
      genres: "genres",
      platforms: "platforms",
      themes: "themes",
      name: "name",
      countryCode: "country code (2 letters, optional)",
    },
    placeholders: {
      title: "e.g. elden ring",
      slug: "e.g. elden-ring",
      originalTitle: "e.g. エルデンリング",
      description: "enter game details/summary...",
      coverImageUrl: "https://example.com/cover.jpg",
      metacriticScore: "0-100",
      hltbMain: "e.g. 30",
      hltbMainEx: "e.g. 50",
      hltbComp: "e.g. 100",
      developers: "nintendo epd, fromsoftware...",
      publishers: "nintendo, bandai namco...",
      genres: "action, rpg, platformer...",
      themes: "fantasy, sci-fi, cyberpunk...",
      platforms: "nintendo switch, pc, playstation 5...",
      developerSlug: "nintendo-epd",
      publisherSlug: "nintendo",
      genreSlug: "action",
      themeSlug: "fantasy",
      platformSlug: "nintendo-switch",
      countryCode: "jp, us, tr, pl...",
      searchRelation: "search {label} (min 3 chars)...",
      filterRelation: "filter {label}...",
      loadingOptions: "loading options...",
      noOptions: "no options found.",
    },
    hints: {
      loading: "loading…",
      minChars: "type at least 3 characters.",
      waiting: "waiting…",
      noMatches: "no matches.",
    },
    errors: {
      titleRequired: "title is required",
      nameRequired: "name is required",
      slugRequired: "slug is required",
      linkFailed: "failed to link/unlink {relationType}.",
      serverError: "server connection error.",
      loadFailed: "failed to load latest game data.",
    },
    deleteConfirm: 'are you sure you want to delete {type} "{itemName}"?',
    pagination: {
      prev: "← prev",
      next: "next →",
      showing: "showing {start}-{end} of {total} items",
      itemsPerPage: "items per page:",
    },
    backToGames: "← back to games",
    editGame: "edit game",
  },

  content: {
    posts: "posts (blog posts)",
    projects: "projects",
    pages: "pages",
    newPost: "+ new post",
    newProject: "+ new project",
    newPage: "+ new page",
    noPosts: "no posts added yet.",
    noProjects: "no projects added yet.",
    noPages: "no pages added yet.",
    table: {
      title: "title",
      status: "status",
      actions: "actions",
    },
    status: {
      published: "published",
      draft: "draft",
    },
    edit: "edit",
  },

  delete: {
    confirm: 'are you sure you want to delete the {type} "{title}"?',
    button: "delete",
    deleting: "deleting...",
  },

  pagination: {
    prev: "← prev",
    next: "next →",
    pageOf: "page {activePage} of {totalPages}",
    itemsPerPage: "items per page:",
  },

  login: {
    backToHome: "← back to home",
    title: "admin login",
    email: "email",
    password: "password",
    emailPlaceholder: "admin@vefacaglar.com",
    passwordPlaceholder: "••••••",
    signIn: "sign in",
    signingIn: "signing in...",
  },

  profile: {
    backToDashboard: "← back to dashboard",
    title: "profile",
    profileInfo: "profile information",
    changePassword: "change password",
    displayName: "display name",
    email: "email",
    username: "username",
    saving: "saving...",
    saveProfile: "save profile",
    updated: "profile updated successfully.",
    currentPassword: "current password",
    newPassword: "new password",
    confirmPassword: "confirm new password",
    changing: "changing...",
    changePasswordBtn: "change password",
    passwordChanged: "password changed successfully.",
    passwordMismatch: "new passwords do not match.",
    passwordTooShort: "new password must be at least 6 characters.",
  },

  forms: {
    backCancel: "← cancel",
    backToDashboard: "← back to dashboard",
    editPage: "edit page",
    addNewPage: "add new page",
    editPost: "edit post",
    addNewPost: "add new post",
    editProject: "edit project",
    addNewProject: "add new project",
    title: "title",
    slug: "slug (url path)",
    excerpt: "excerpt",
    content: "content (markdown / mdx)",
    coverImageUrl: "cover image url",
    publishStatus: "publish status",
    seoSettings: "seo settings (optional)",
    seoTitle: "seo title",
    seoDescription: "seo description",
    summary: "summary (short description)",
    startedAt: "started at",
    endedAt: "ended at (optional)",
    sortOrder: "sort order",
    featuredProject: "featured project",
    githubUrl: "github repo url (optional)",
    liveUrl: "live demo url (optional)",
    saving: "saving...",
    saveChanges: "save changes",
    publishPage: "publish page",
    publishPost: "publish post",
    publishProject: "publish project",
    placeholders: {
      coverImageUrl: "https://example.com/image.png",
      githubUrl: "https://github.com/username/repo",
      liveUrl: "https://example.com",
      mdxPost: "# title\n\nwrite your content in mdx/markdown format...",
      mdxPage: "# page title\n\nwrite page content in mdx/markdown format...",
      mdxProject: "# project details\n\nwrite about features, challenges, and architecture in markdown...",
    },
  },

  localization: {
    triggerTitle: "add turkish translation for {label}",
    triggerText: "tr",
    modalTitle: "turkish translation: {label}",
    close: "close",
    language: "language",
    languageOption: "turkish",
    loadingPlaceholder: "loading translation...",
    writePlaceholder: "write turkish translation for {label}...",
    cancel: "cancel",
    save: "save",
    saving: "saving...",
    saved: "localization saved.",
    error: "please enter a translation.",
  },

  packages: {
    title: "packages",
    newPackage: "+ new package",
    noPackages: "no packages added yet.",
    editPackage: "edit package",
    addNewPackage: "add new package",
    name: "package name",
    slug: "slug (url path)",
    description: "description",
    nugetUrl: "nuget url (optional)",
    npmUrl: "npm url (optional)",
    githubUrl: "github url (optional)",
    latestVersion: "latest version",
    isActive: "active / visible on site",
    deleteConfirm: 'are you sure you want to delete package "{name}"?',
    saveChanges: "save changes",
    publishPackage: "publish package",
    saving: "saving...",
  },
} as const;

export default dashboardStrings;
